package com.components.hospitalcaresystem.presentation.theme

import androidx.compose.ui.graphics.Color

val Purple80 = Color(0xFFD0BCFF)
val PurpleGrey80 = Color(0xFFCCC2DC)
val Pink80 = Color(0xFFEFB8C8)

val Purple40 = Color(0xFF6650a4)
val PurpleGrey40 = Color(0xFF625b71)
val Pink40 = Color(0xFF7D5260)

//New Colors
val md_theme_light_primary = Color(0xFF42C6C6)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFFFFFFF)
val md_theme_light_onPrimaryContainer = Color(0xFF000000)
val md_theme_light_secondary = Color(0xFF6F5B40)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF7FFFE)
val md_theme_light_onSecondaryContainer = Color(0xFF000000)
val md_theme_light_tertiary = Color(0xFF51643F)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD4EABB)
val md_theme_light_onTertiaryContainer = Color(0xFF102004)
val md_theme_light_error = Color(0xFFE25508)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFFFFFF)
val md_theme_light_onBackground = Color(0xFF0C0D0D)
val md_theme_light_surface = Color(0xFFFFFFFF)
val md_theme_light_onSurface = Color(0xFF1F1B16)
val md_theme_light_surfaceVariant = Color(0xFF9C9C9C)
val md_theme_light_onSurfaceVariant = Color(0xFFCECFD7)
val md_theme_light_outline = Color(0xFFD0D0D0)
val md_theme_light_inverseOnSurface = Color(0xFFF9EFE7)
val md_theme_light_inverseSurface = Color(0xFF34302A)
val md_theme_light_inversePrimary = Color(0xFFFFB951)
val md_theme_light_shadow = Color(0xFFE7E7E7)
val md_theme_light_surfaceTint = Color(0xFF825500)
val md_theme_light_outlineVariant = Color(0xFFD3C4B4)
val md_theme_light_scrim = Color(0xFF000000)
val md_theme_light_placeHolder = Color(0xFF777777)
val md_daily_limits_filled_primary = Color(0xFF42C6C6)
val md_daily_limits_unfilled_primary = Color(0xFFD9EEDB)

val md_monthly_limits_filled_primary = Color(0xFFEC6F2B)
val md_monthly_limits_unfilled_primary = Color(0xFFFFDED2)
val md_unselected_tab_primary = Color(0xFFF3F4FA)


val md_theme_dark_primary = Color(0xFF42C6C6)
val md_theme_dark_onPrimary = Color(0xFFFFFFFF)
val md_theme_dark_primaryContainer = Color(0xFF0B242C)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFFFFF)
val md_theme_dark_secondary = Color(0xFFDDC2A1)
val md_theme_dark_onSecondary = Color(0xFF3E2D16)
val md_theme_dark_secondaryContainer = Color(0xFFF7FFFE)
val md_theme_dark_onSecondaryContainer = Color(0xFF000000)
val md_theme_dark_tertiary = Color(0xFFB8CEA1)
val md_theme_dark_onTertiary = Color(0xFF243515)
val md_theme_dark_tertiaryContainer = Color(0xFF3A4C2A)
val md_theme_dark_onTertiaryContainer = Color(0xFFD4EABB)
val md_theme_dark_error = Color(0xFFE25508)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFFFFFFFF)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF031D25)
val md_theme_dark_onBackground = Color(0xFFFFFFFF)
val md_theme_dark_surface = Color(0xFF031D25)
val md_theme_dark_onSurface = Color(0xFFEAE1D9)
val md_theme_dark_surfaceVariant = Color(0xFF9C9C9C)
val md_theme_dark_onSurfaceVariant = Color(0xFFCECFD7)
val md_theme_dark_outline = Color(0xFFD0D0D0)
val md_theme_dark_inverseOnSurface = Color(0xFF1F1B16)
val md_theme_dark_inverseSurface = Color(0xFFEAE1D9)
val md_theme_dark_inversePrimary = Color(0xFF825500)
val md_theme_dark_shadow = Color(0xEBE8FF80)
val md_theme_dark_surfaceTint = Color(0xFFFFB951)
val md_theme_dark_outlineVariant = Color(0xFF4F4539)
val md_theme_dark_scrim = Color(0xFF000000)
val md_theme_dark_placeHolder = Color(0xFF777777)
val Transparent = Color(0x00FFFFFF)
val BlackOp70 = Color(0x80000000)
val BlackOp50 = Color(0xB3000000)
val BORDER_GRAY = Color(0xFFDCDCDC)
val BORDER_GRAY2 = Color(0x2ADCDCDC)
val LightOrange60 = Color(0xFFE5AD99)
val LightOrange40 = Color(0xFFFFE6DD)
val Orange90 = Color(0xFFE25508)